<a href="https://colab.research.google.com/github/praneeth0210/Machine_learning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
x=[i for i in range(10)]

In [ ]:
print(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
y = [2*i for i in range(10)]

In [ ]:
print(y)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [ ]:
import numpy as np

In [ ]:
line = np.empty([10,10])

In [ ]:
line

array([[4.67905697e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        6.60181103e-310, 6.60181103e-310, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.0

In [ ]:
line=np.arange(50)

In [ ]:
line

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
line.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
line.flatten()
line

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
line.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
line.ravel()
line

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
a=line.sum(axis=0)
a

1225

In [ ]:
a=np.ravel(line)
a=a.reshape(5,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
line.shape

(50,)

In [ ]:
line1=[i for i in line.flat]
line1

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49]

In [ ]:
a.shape

(5, 10)

In [ ]:
line.shape

(50,)

In [ ]:
a=[[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
ar=np.array(a)

In [ ]:
ar.flat

In [ ]:
ar.ndim

2

In [ ]:
a.nbytes

400

In [ ]:
a.max()

49

In [ ]:
a.min()

0

In [ ]:
a=np.random.randint(0,50,50)
a

array([38, 35,  8,  1,  2,  5, 10,  0, 30, 25, 15, 44, 45,  7,  0, 14, 15,
       10,  7, 16, 18, 10, 36,  7, 48, 31, 34, 23, 34, 15, 41, 19, 18,  6,
       17, 39, 37, 31,  9, 43, 18, 43, 36, 20,  9,  7, 40,  7, 24,  7])

In [ ]:
a.argmin()

7

In [ ]:
a=a.reshape(2,25)
a

array([[38, 35,  8,  1,  2,  5, 10,  0, 30, 25, 15, 44, 45,  7,  0, 14,
        15, 10,  7, 16, 18, 10, 36,  7, 48],
       [31, 34, 23, 34, 15, 41, 19, 18,  6, 17, 39, 37, 31,  9, 43, 18,
        43, 36, 20,  9,  7, 40,  7, 24,  7]])

In [ ]:
a.argsort(axis=0)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        0, 0, 0]])

In [ ]:
a.sort()
a

array([[ 0,  0,  1,  2,  5,  7,  7,  7,  8, 10, 10, 10, 14, 15, 15, 16,
        18, 25, 30, 35, 36, 38, 44, 45, 48],
       [ 6,  7,  7,  7,  9,  9, 15, 17, 18, 18, 19, 20, 23, 24, 31, 31,
        34, 34, 36, 37, 39, 40, 41, 43, 43]])

In [ ]:
array=np.random.randint(0,50,50)
array=array.reshape(2,25)
array

array([[47, 20, 38, 49, 16, 35, 30, 21, 28, 15,  1, 34, 47, 47,  5, 25,
        39, 27, 15, 49, 38, 15, 44,  3,  8],
       [19, 47, 21, 40, 37, 21,  7, 38,  0, 48, 19, 30, 39, 28, 43, 40,
        28, 45, 21, 23, 28,  0, 45, 42, 49]])

In [ ]:
a+array

array([[47, 20, 39, 51, 21, 42, 37, 28, 36, 25, 11, 44, 61, 62, 20, 41,
        57, 52, 45, 84, 74, 53, 88, 48, 56],
       [25, 54, 28, 47, 46, 30, 22, 55, 18, 66, 38, 50, 62, 52, 74, 71,
        62, 79, 57, 60, 67, 40, 86, 85, 92]])

In [ ]:
a*array

array([[   0,    0,   38,   98,   80,  245,  210,  147,  224,  150,   10,
         340,  658,  705,   75,  400,  702,  675,  450, 1715, 1368,  570,
        1936,  135,  384],
       [ 114,  329,  147,  280,  333,  189,  105,  646,    0,  864,  361,
         600,  897,  672, 1333, 1240,  952, 1530,  756,  851, 1092,    0,
        1845, 1806, 2107]])

In [ ]:
array=array.reshape(25,2)

In [ ]:
np.matmul(a,array)

array([[13564, 13593],
       [18847, 17207]])

In [ ]:
array=np.sqrt(array)
array.astype(np.int8)

array([[6, 4],
       [6, 7],
       [4, 5],
       [5, 4],
       [5, 3],
       [1, 5],
       [6, 6],
       [2, 5],
       [6, 5],
       [3, 7],
       [6, 3],
       [6, 1],
       [2, 4],
       [6, 4],
       [6, 6],
       [4, 2],
       [6, 0],
       [6, 4],
       [5, 6],
       [5, 6],
       [6, 5],
       [6, 4],
       [4, 5],
       [0, 6],
       [6, 7]], dtype=int8)